
ARDUINO_DIR = $(HOME)/Projects/Arduino/arduino-1.8.6
ARDMK_DIR = $(HOME)/Projects/Arduino/Arduino-Makefile/
AVR_TOOLS_DIR = $(ARDUINO_DIR)/hardware/tools/avr/
BOARD_TAG    = uno
ARDUINO_LIBS = qpn_avr
MONITOR_BAUDRATE = 115200
#USER_LIB_PATH = $(ARDUINO_DIR)/hardware/arduino/avr/libraries/

include $(ARDMK_DIR)/Arduino.mk


