
## Modify this according to installation location
ASM_DIR = $(HOME)/Projects/ArduinoStateMachine/

ARDUINO_DIR = $(ASM_DIR)/arduino-1.8.6
ARDMK_DIR = $(ASM_DIR)/Arduino-Makefile/
AVR_TOOLS_DIR = $(ARDUINO_DIR)/hardware/tools/avr/
BOARD_TAG    = uno
ARDUINO_LIBS = qpn_avr
MONITOR_BAUDRATE = 115200

include $(ARDMK_DIR)/Arduino.mk


